stages: 
    - publish
    - deployment

publish:
    stage: publish
    tags:
        - docker
    image: docker:latest
    services:
        - docker:dind
    script:
        - docker login --username ${DOCKER_ID} -p ${DOCKER_PASS}
        - docker build
          --build-arg IMAGE_VERSION=${CI_COMMIT_REF_NAME/master/latest}
          -t ${DOCKER_ID}/${CI_PROJECT_NAME}:${CI_COMMIT_REF_NAME/master/latest} .
        - docker push ${DOCKER_ID}/${CI_PROJECT_NAME}:${CI_COMMIT_REF_NAME/master/latest}

deployment-dev:
    stage: deployment
    tags:
        - openshift
    script:
        - oc login ${OPENSHIFT_URL} -u ${OPENSHIFT_ID} -p ${OPENSHIFT_PASS} --insecure-skip-tls-verify=true
        - oc project t-challenge-${CI_JOB_NAME}
        - helm upgrade tmongodb mongodb
        #- oc apply -f mongo-deployment.yml
        - rm -Rf /home/gitlab-runner/builds/${CI_RUNNER_SHORT_TOKEN}/0/ya-makariy/
    environment:
        name: dev
        url: https://openshift.devops.t-systems.ru:8443/console/project/t-challenge-${CI_JOB_NAME}/overview


deployment-prod:
    stage: deployment
    tags:
        - openshift
    script:
        - oc login ${OPENSHIFT_URL} -u ${OPENSHIFT_ID} -p ${OPENSHIFT_PASS} --insecure-skip-tls-verify=true
        - oc project t-challenge-${CI_JOB_NAME}
        - helm upgrade tmongodb mongodb
        #- oc apply -f mongo-deployment.yml
        - rm -Rf /home/gitlab-runner/builds/${CI_RUNNER_SHORT_TOKEN}/0/ya-makariy/
    environment:
        name: dev
        url: https://openshift.devops.t-systems.ru:8443/console/project/t-challenge-${CI_JOB_NAME}/overview
    when: manual
